# =====================
# build stage
# =====================
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build

# =====================
# runtime stage
# =====================
FROM nginx:1.27-alpine

# nginx 設定
COPY nginx.conf /etc/nginx/conf.d/default.conf

# ビルド成果物を配置
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
