openapi: 3.0.3
info:
  title: TypeDocによるドキュメント作成
  version: 1.0.0
  description: |
    本ドキュメントはfrontendのローカル開発環境で、ソースファイル個々のTypeDocによるドキュメント作成について示しています。

    ## 1. JSDocによるドキュメント作成
    - Visual Studio Codeでターミナルを開き、以下を実行。
      ```bash
      npm install --save-dev typedoc typedoc-plugin-markdown
      ```
      - 全ファイルのTypeDocを実施する場合
        ```bash
        npx typedoc
        ```
      - 特定のファイルのTypeDocを実施する場合
        ```bash
        npx typedoc src/pages/[ファイル名]
        ```

    ## 2. 作成されたドキュメントの確認
    - ブラウザにて以下を確認。
      ```bash
      [リポジトリ名]/frontend/docs/index.html
      ```

    ## A. 参考URL
    - JSDoc 公式ドキュメント
      ```bash
      https://jsdoc.app/?utm_source=chatgpt.com
      ```
    - JSDoc GitHub リポジトリ
      ```bash
      https://github.com/jsdoc/jsdoc?utm_source=chatgpt.com
      ```

paths: {}
